### ISSUE TITLE
Can't access @workspace

### ISSUE THREAD

**Issue by AHHusam** [microsoft/vscode-copilot-release#3469]
Type: <b>Bug</b>

(intermediate value)(intermediate value)(intermediate value)?.map is not a function

Extension version: 0.23.2024102903
VS Code version: Code 1.96.0 (Universal) (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Darwin arm64 23.6.0
Modes:

**Comment by AHHusam** [comment]
Got this error after updating VSCode to 1.96.1
https://github.com/microsoft/vscode-copilot-release/issues/3474

**Comment by kieferrm** [comment]
Pls see my comment over here https://github.com/microsoft/vscode-copilot-release/issues/3474#issuecomment-2559894867.

**Comment by mjbvz** [comment]
This happens when you accidentally run an old pre-release version of Copilot chat on the latest stable release of VS Code. Please switch to use the release version of the copilot chat extension. This can be done on the extension's page:

<img width="923" alt="Image" src="https://github.com/user-attachments/assets/96aa91ce-2ce8-4cd9-93f1-1bc24d5d7094" />

This old pre-release version has a bug that prevents you from getting newer releases automatically
